import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Fjalla_One } from 'next/font/google'
import ButtonProject from "./components/ButtonProjects";
import { db } from "@/src/data/drizzle";
import { adaProjects, promotionsAda } from "@/src/data/schema";
import { eq } from "drizzle-orm";
import Link from "next/link";
import SelectProjects from "./components/SelectProjects";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fjallaOne = Fjalla_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-logo',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const promotions = await db.select().from(promotionsAda)
  //console.log(promotions)
  const projects = await db.select().from(adaProjects)

  //deux manière pour récupérer l'ID selon une condition
  // const [promoAdaId] = await db.select().from(promotionsAda).where(eq(promotionsAda.name, "Frida"))

  // console.log(promoAdaId.id)

  // const [test] = await db.query.promotionsAda.findMany({
  //   where: eq(promotionsAda.name, "Frida")
  // })

  // console.log(test.id)

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <section className="bg-(--bg-gray) m-2 p-5 rounded-[10px] flex items-center justify-between gap-5">
            <Link href={"/"}>
              <h1 className={`text-4xl ${fjallaOne.className}`} style={{ color: 'var(--color-logo)' }}>ADAVERSE</h1>
            </Link>
            <section className="flex flex-row gap-5">
            <SelectProjects/>
            <ButtonProject promotions={promotions} projects={projects}/>
            </section>
          </section>
        </header>

        <div className="m-8">
        {children}
        </div>
      </body>
    </html>
  );
}
